server_approach_shelf:
  ros__parameters:

    use_sim_time: false
    # Kinematics parameters
    vel_min_linear_x: 0.02
    vel_min_angular_z: 0.03
    vel_max_linear_x: 0.15
    vel_max_angular_z: 0.4
    
    # Control parameters
    kp_angular: 0.5
    kp_lineal: 0.3

    # Control error
    distance_approach_target_error_back: 0.1
    distance_approach_target_error: 0.01
    angle_approach_target_error: 0.01
    laser_min_range: 0.3
    distance_for_back_frame_publish: 1.0


